# Generated by Django 6.0.7 on 2026-08-14 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_one', to='profiles.profile')),
                ('profile_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_two', to='profiles.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile_one', 'profile_two'), name='unique_profile_match')],
            },
        ),
    ]
