# Generated by Django 6.0.7 on 2026-08-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='action',
            field=models.CharField(choices=[('LIKE', 'Like'), ('PASS', 'Pass'), ('UNLIKE', 'Unlike')], max_length=10),
        ),
    ]
